//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 11:26:37 AM EDT 
//


package gov.mlms.cciio.cms.shopagreementstatusresponsetype;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.mlms.cciio.cms.cciiowebservicecommontype.UsStateType;


/**
 * <p>Java class for npnEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="npnEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="npnId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="npnEntityType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Individual NPN"/>
 *               &lt;enumeration value="Business NPN"/>
 *               &lt;enumeration value="Web-Based NPN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="npnEntityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="npnState" type="{http://cms.cciio.mlms.gov/CCIIOWebServiceCommonType}usStateType" maxOccurs="51" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "npnEntityType", propOrder = {
    "npnId",
    "npnEntityType",
    "npnEntityName",
    "npnState"
})
public class NpnEntityType {

    @XmlElement(required = true)
    protected String npnId;
    @XmlElement(required = true)
    protected String npnEntityType;
    @XmlElement(required = true)
    protected String npnEntityName;
    protected List<UsStateType> npnState;

    /**
     * Gets the value of the npnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpnId() {
        return npnId;
    }

    /**
     * Sets the value of the npnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpnId(String value) {
        this.npnId = value;
    }

    /**
     * Gets the value of the npnEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpnEntityType() {
        return npnEntityType;
    }

    /**
     * Sets the value of the npnEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpnEntityType(String value) {
        this.npnEntityType = value;
    }

    /**
     * Gets the value of the npnEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpnEntityName() {
        return npnEntityName;
    }

    /**
     * Sets the value of the npnEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpnEntityName(String value) {
        this.npnEntityName = value;
    }

    /**
     * Gets the value of the npnState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npnState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNpnState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsStateType }
     * 
     * 
     */
    public List<UsStateType> getNpnState() {
        if (npnState == null) {
            npnState = new ArrayList<UsStateType>();
        }
        return this.npnState;
    }

}
