//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 11:26:37 AM EDT 
//


package gov.mlms.cciio.cms.shopagreementstatusresponsetype;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.mlms.cciio.cms.cciiowebservicecommontype.StatusType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shopAgreement" type="{http://cms.cciio.mlms.gov/ShopAgreementStatusResponseType}shopAgreementType" maxOccurs="3"/>
 *         &lt;element name="npnEntity" type="{http://cms.cciio.mlms.gov/ShopAgreementStatusResponseType}npnEntityType" maxOccurs="3"/>
 *         &lt;element name="operationStatus" type="{http://cms.cciio.mlms.gov/CCIIOWebServiceCommonType}StatusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userId",
    "shopAgreement",
    "npnEntity",
    "operationStatus"
})
@XmlRootElement(name = "shopAgreementStatusResponse")
public class ShopAgreementStatusResponse {

    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected List<ShopAgreementType> shopAgreement;
    @XmlElement(required = true)
    protected List<NpnEntityType> npnEntity;
    @XmlElement(required = true)
    protected StatusType operationStatus;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the shopAgreement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shopAgreement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShopAgreement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShopAgreementType }
     * 
     * 
     */
    public List<ShopAgreementType> getShopAgreement() {
        if (shopAgreement == null) {
            shopAgreement = new ArrayList<ShopAgreementType>();
        }
        return this.shopAgreement;
    }

    /**
     * Gets the value of the npnEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npnEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNpnEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NpnEntityType }
     * 
     * 
     */
    public List<NpnEntityType> getNpnEntity() {
        if (npnEntity == null) {
            npnEntity = new ArrayList<NpnEntityType>();
        }
        return this.npnEntity;
    }

    /**
     * Gets the value of the operationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getOperationStatus() {
        return operationStatus;
    }

    /**
     * Sets the value of the operationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setOperationStatus(StatusType value) {
        this.operationStatus = value;
    }

}
