//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.11 at 11:26:37 AM EDT 
//


package gov.mlms.cciio.cms.shopagreementstatusresponsetype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shopAgreementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shopAgreementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shopAgreementName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shopAgreementStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shopAgreementExperationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shopAgreemenAcquiredDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shopAgreementType", propOrder = {
    "shopAgreementName",
    "shopAgreementStatus",
    "shopAgreementExperationDate",
    "shopAgreemenAcquiredDate"
})
public class ShopAgreementType {

    @XmlElement(required = true)
    protected String shopAgreementName;
    @XmlElement(required = true)
    protected String shopAgreementStatus;
    @XmlElement(required = true)
    protected String shopAgreementExperationDate;
    @XmlElement(required = true)
    protected String shopAgreemenAcquiredDate;

    /**
     * Gets the value of the shopAgreementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopAgreementName() {
        return shopAgreementName;
    }

    /**
     * Sets the value of the shopAgreementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopAgreementName(String value) {
        this.shopAgreementName = value;
    }

    /**
     * Gets the value of the shopAgreementStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopAgreementStatus() {
        return shopAgreementStatus;
    }

    /**
     * Sets the value of the shopAgreementStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopAgreementStatus(String value) {
        this.shopAgreementStatus = value;
    }

    /**
     * Gets the value of the shopAgreementExperationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopAgreementExperationDate() {
        return shopAgreementExperationDate;
    }

    /**
     * Sets the value of the shopAgreementExperationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopAgreementExperationDate(String value) {
        this.shopAgreementExperationDate = value;
    }

    /**
     * Gets the value of the shopAgreemenAcquiredDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShopAgreemenAcquiredDate() {
        return shopAgreemenAcquiredDate;
    }

    /**
     * Sets the value of the shopAgreemenAcquiredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShopAgreemenAcquiredDate(String value) {
        this.shopAgreemenAcquiredDate = value;
    }

}
