//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package org.mlms.cciio.ibm.cms.mlmstrainingstatusservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.mlms.cciio.ibm.cms.retrievetrainingcompletionstatusrequest.UserId;
import org.mlms.cciio.ibm.cms.retrievetrainingcompletionstatustype.RetrieveTrainingCompletionStatusResponse;

@WebService(name = "MLMSTrainingStatusService", targetNamespace = "http://cms.ibm.cciio.mlms.org/MLMSTrainingStatusService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.mlms.cciio.cms.cciiowebservicecommontype.ObjectFactory.class,
    org.mlms.cciio.ibm.cms.retrievetrainingcompletionstatusrequest.ObjectFactory.class,
    org.mlms.cciio.ibm.cms.retrievetrainingcompletionstatustype.ObjectFactory.class
})
public interface MLMSTrainingStatusService {


    /**
     * 
     * @param userId
     * @return
     *     returns org.mlms.cciio.ibm.cms.retrievetrainingcompletionstatustype.RetrieveTrainingCompletionStatusResponse
     */
    @WebMethod(operationName = "RetrieveTrainingCompletionStatus", action = "http://cms.ibm.cciio.mlms.org/MLMSTrainingStatusService/RetrieveTrainingCompletionStatus")
    @WebResult(name = "RetrieveTrainingCompletionStatusResponse", targetNamespace = "http://cms.ibm.cciio.mlms.org/RetrieveTrainingCompletionStatusType", partName = "trainingCompletionStatus")
    public RetrieveTrainingCompletionStatusResponse retrieveTrainingCompletionStatus(
        @WebParam(name = "userId", targetNamespace = "http://cms.ibm.cciio.mlms.org/RetrieveTrainingCompletionStatusRequest", partName = "userId")
        UserId userId);

}
