//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 04:17:35 PM EDT 
//


package gov.mlms.cciio.cms.cciioexternalcommontype;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.mlms.cciio.cms.cciioexternalcommontype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StatusCode_QNAME = new QName("http://cms.cciio.mlms.gov/CCIIOExternalCommonType", "StatusCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.mlms.cciio.cms.cciioexternalcommontype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalStatusCodeType }
     * 
     */
    public ExternalStatusCodeType createExternalStatusCodeType() {
        return new ExternalStatusCodeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalStatusCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cms.cciio.mlms.gov/CCIIOExternalCommonType", name = "StatusCode")
    public JAXBElement<ExternalStatusCodeType> createStatusCode(ExternalStatusCodeType value) {
        return new JAXBElement<ExternalStatusCodeType>(_StatusCode_QNAME, ExternalStatusCodeType.class, null, value);
    }

}
