//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package org.mlms.cciio.ibm.cms.retrievetrainingcompletionstatustype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for certificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="certificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="certificationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationExperationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "certificationType", propOrder = {

})
public class CertificationType {

    @XmlElement(required = true)
    protected String certificationId;
    @XmlElement(required = true)
    protected String certificationName;
    @XmlElement(required = true)
    protected String certificationStatus;
    @XmlElement(required = true)
    protected String certificationYear;
    @XmlElement(required = true)
    protected String certificationExperationDate;

    /**
     * Gets the value of the certificationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationId() {
        return certificationId;
    }

    /**
     * Sets the value of the certificationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationId(String value) {
        this.certificationId = value;
    }

    /**
     * Gets the value of the certificationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationName() {
        return certificationName;
    }

    /**
     * Sets the value of the certificationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationName(String value) {
        this.certificationName = value;
    }

    /**
     * Gets the value of the certificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationStatus() {
        return certificationStatus;
    }

    /**
     * Sets the value of the certificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationStatus(String value) {
        this.certificationStatus = value;
    }

    /**
     * Gets the value of the certificationYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationYear() {
        return certificationYear;
    }

    /**
     * Sets the value of the certificationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationYear(String value) {
        this.certificationYear = value;
    }
    /**
     * Gets the value of the certificationExperationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationExperationDate() {
        return certificationExperationDate;
    }

    /**
     * Sets the value of the certificationExperationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationExperationDate(String value) {
        this.certificationExperationDate = value;
    }

}
