//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.checkmlmsdbstatusrequest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.mlms.cciio.cms.checkmlmsdbstatusrequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CheckMLMSDBStatusRequestElement_QNAME = new QName("http://cms.cciio.mlms.gov/CheckMLMSDBStatusRequest", "CheckMLMSDBStatusRequestElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.mlms.cciio.cms.checkmlmsdbstatusrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckMLMSDBStatusRequestType }
     * 
     */
    public CheckMLMSDBStatusRequestType createCheckMLMSDBStatusRequestType() {
        return new CheckMLMSDBStatusRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckMLMSDBStatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cms.cciio.mlms.gov/CheckMLMSDBStatusRequest", name = "CheckMLMSDBStatusRequestElement")
    public JAXBElement<CheckMLMSDBStatusRequestType> createCheckMLMSDBStatusRequestElement(CheckMLMSDBStatusRequestType value) {
        return new JAXBElement<CheckMLMSDBStatusRequestType>(_CheckMLMSDBStatusRequestElement_QNAME, CheckMLMSDBStatusRequestType.class, null, value);
    }

}
