//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.checkmlmsdbstatusresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.mlms.cciio.cms.cciiowebservicecommontype.StatusType;


/**
 * <p>Java class for CheckMLMSDBStatusResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckMLMSDBStatusResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://cms.cciio.mlms.gov/CheckMLMSDBStatusResponse}CheckMLMSDBStatusResponseElement"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckMLMSDBStatusResponseType", propOrder = {
    "checkMLMSDBStatusResponseElement"
})
public class CheckMLMSDBStatusResponseType {

    @XmlElement(name = "CheckMLMSDBStatusResponseElement", required = true)
    protected StatusType checkMLMSDBStatusResponseElement;

    /**
     * Gets the value of the checkMLMSDBStatusResponseElement property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getCheckMLMSDBStatusResponseElement() {
        return checkMLMSDBStatusResponseElement;
    }

    /**
     * Sets the value of the checkMLMSDBStatusResponseElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setCheckMLMSDBStatusResponseElement(StatusType value) {
        this.checkMLMSDBStatusResponseElement = value;
    }

}
