//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.cms.hios.soa.assister;

import gov.cms.hios.AssisterRequest;
import gov.cms.hios.AssisterResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "RetrieveAssisterPortType", targetNamespace = "http://soa.jboss.org/Assister")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.cms.hios.ObjectFactory.class,
    gov.cms.hios_api_types.ObjectFactory.class
})
public interface RetrieveAssisterPortType {


    /**
     * 
     * @param in
     * @return
     *     returns gov.cms.hios.AssisterResponse
     */
    @WebMethod(operationName = "RetrieveAssisterOp", action = "http://soa.jboss.org/Assister/RetrieveAssisterOpResp")
    @WebResult(name = "AssisterResponse", targetNamespace = "http://cms.gov/hios", partName = "out")
    public AssisterResponse retrieveAssisterOp(
        @WebParam(name = "AssisterRequest", targetNamespace = "http://cms.gov/hios", partName = "in")
        AssisterRequest in);

}
