//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.hios.mlms.cciio.cms.hiosassisteragreementstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.hios.mlms.cciio.cms.assisteragreementstatusrequest.AcquiredDatetime;
import gov.hios.mlms.cciio.cms.assisteragreementstatusresponse.AssisterAgreementStatusResponse;

@WebService(name = "HiosAssisterAgreementStatus", targetNamespace = "http://cms.cciio.mlms.hios.gov/HiosAssisterAgreementStatus/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.hios.mlms.cciio.cms.assisteragreementstatusrequest.ObjectFactory.class,
    gov.hios.mlms.cciio.cms.assisteragreementstatusresponse.ObjectFactory.class,
    gov.mlms.cciio.cms.cciiowebservicecommontype.ObjectFactory.class
})
public interface HiosAssisterAgreementStatus {


    /**
     * 
     * @param certificationDateTime
     * @return
     *     returns gov.hios.mlms.cciio.cms.assisteragreementstatusresponse.AssisterAgreementStatusResponse
     */
    @WebMethod(operationName = "RetrieveAssisterAgreementStatus", action = "http://cms.cciio.mlms.hios.gov/HiosAssisterAgreementStatus/RetrieveAssisterAgreementStatus")
    @WebResult(name = "assisterAgreementStatusResponse", targetNamespace = "http://cms.cciio.mlms.hios.gov/AssisterAgreementStatusResponse", partName = "assisterAgreementStatusInfo")
    public AssisterAgreementStatusResponse retrieveAssisterAgreementStatus(
        @WebParam(name = "acquiredDatetime", targetNamespace = "http://cms.cciio.mlms.hios.gov/AssisterAgreementStatusRequest", partName = "certificationDateTime")
        AcquiredDatetime certificationDateTime);

}
