//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package util.mlms.cciio.cms.mlmsshopuserprofile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.mlms.cciio.cms.shopuserprofileresponsetype.ShopUserProfileResponseType;

@WebService(name = "MLMSShopUserProfile", targetNamespace = "http://cms.cciio.mlms.util/MLMSShopUserProfile/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.mlms.cciio.cms.cciiowebservicecommontype.ObjectFactory.class,
    gov.mlms.cciio.cms.mlmsshopuserprofilecommontype.ObjectFactory.class,
    gov.mlms.cciio.cms.shopuserprofilerequesttype.ObjectFactory.class,
    gov.mlms.cciio.cms.shopuserprofileresponsetype.ObjectFactory.class,
    util.mlms.cciio.cms.mlmsshopuserprofile.ObjectFactory.class
})
public interface MLMSShopUserProfile {


    /**
     * 
     * @param userId
     * @return
     *     returns gov.mlms.cciio.cms.shopuserprofileresponsetype.ShopUserProfileResponseType
     */
    @WebMethod(operationName = "RetrieveShopUserProfile", action = "http://cms.cciio.mlms.util/MLMSShopUserProfile/RetrieveShopUserProfile")
    @WebResult(name = "ShopUserProfile", targetNamespace = "http://cms.cciio.mlms.gov/ShopUserProfileResponseType", partName = "ShopUserProfile")
    public ShopUserProfileResponseType retrieveShopUserProfile(
        @WebParam(name = "UserId", targetNamespace = "http://cms.cciio.mlms.gov/ShopUserProfileRequestType", partName = "UserId")
        String userId);

}
