//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package util.mlms.cciio.cms.mlmsshopuserprofile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the util.mlms.cciio.cms.mlmsshopuserprofile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RetrieveShopUserProfileRequest_QNAME = new QName("http://cms.cciio.mlms.util/MLMSShopUserProfile/", "RetrieveShopUserProfileRequest");
    private final static QName _ShopUserProfile_QNAME = new QName("http://cms.cciio.mlms.util/MLMSShopUserProfile/", "ShopUserProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: util.mlms.cciio.cms.mlmsshopuserprofile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cms.cciio.mlms.util/MLMSShopUserProfile/", name = "RetrieveShopUserProfileRequest")
    public JAXBElement<String> createRetrieveShopUserProfileRequest(String value) {
        return new JAXBElement<String>(_RetrieveShopUserProfileRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cms.cciio.mlms.util/MLMSShopUserProfile/", name = "ShopUserProfile")
    public JAXBElement<String> createShopUserProfile(String value) {
        return new JAXBElement<String>(_ShopUserProfile_QNAME, String.class, null, value);
    }

}
