//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.mlmsutil.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.mlms.cciio.cms.cciiowebservicecommontype.StatusType;
import gov.mlms.cciio.cms.checkmlmsdbstatusrequest.CheckMLMSDBStatusRequestType;

@WebService(name = "MLMSUtil", targetNamespace = "http://cms.cciio.mlms.util/MLMSUtil/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.mlms.cciio.cms.cciiowebservicecommontype.ObjectFactory.class,
    gov.mlms.cciio.cms.checkmlmsdbstatusrequest.ObjectFactory.class,
    gov.mlms.cciio.cms.checkmlmsdbstatusresponse.ObjectFactory.class
})
public interface MLMSUtil {


    /**
     * 
     * @param checkMLMSDBStatusRequest
     * @return
     *     returns gov.mlms.cciio.cms.cciiowebservicecommontype.StatusType
     */
    @WebMethod(operationName = "CheckMLMSDBStatus", action = "http://cms.cciio.mlms.util/MLMSUtil/CheckMLMSDBStatus")
    @WebResult(name = "CheckMLMSDBStatusResponseElement", targetNamespace = "http://cms.cciio.mlms.gov/CheckMLMSDBStatusResponse", partName = "CheckMLMSDBStatusResponse")
    public StatusType checkMLMSDBStatus(
        @WebParam(name = "CheckMLMSDBStatusRequestElement", targetNamespace = "http://cms.cciio.mlms.gov/CheckMLMSDBStatusRequest", partName = "CheckMLMSDBStatusRequest")
        CheckMLMSDBStatusRequestType checkMLMSDBStatusRequest);

}
