//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.hhs.cms.eidm.ws.waas.api.waasaplicationinfov6;

import javax.xml.ws.WebFault;
import gov.hhs.cms.eidm.ws.waas.domain.common.FaultType;

@WebFault(name = "RetrieveAppDetailsFault", targetNamespace = "http://types.waasaplicationinfov6.api.waas.ws.eidm.cms.hhs.gov")
public class RetrieveAppDetailsFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RetrieveAppDetailsFault(String message, FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RetrieveAppDetailsFault(String message, FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: gov.hhs.cms.eidm.ws.waas.domain.common.FaultType
     */
    public FaultType getFaultInfo() {
        return faultInfo;
    }

}
