//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.mlmsabvendorcompletion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.mlms.cciio.cms.externalvendorrequesttype.ExternalVendorRequestType;
import gov.mlms.cciio.cms.externalvendorresponsetype.ExternalVendorResponseType;

@WebService(name = "MLMSABVendorCompletion", targetNamespace = "http://cms.cciio.mlms.gov/MLMSABVendorCompletion/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.mlms.cciio.cms.cciiowebservicecommontype.ObjectFactory.class,
    gov.mlms.cciio.cms.externalvendorrequesttype.ObjectFactory.class,
    gov.mlms.cciio.cms.externalvendorresponsetype.ObjectFactory.class
})
public interface MLMSABVendorCompletion {


    /**
     * 
     * @param completionRecord
     * @return
     *     returns gov.mlms.cciio.cms.externalvendorresponsetype.ExternalVendorResponseType
     */
    @WebMethod(operationName = "ReceiveABVendorCompletion", action = "http://cms.cciio.mlms.gov/MLMSABVendorCompletion/ReceiveABVendorCompletion")
    @WebResult(name = "ExternalVendorResponse", targetNamespace = "http://cms.cciio.mlms.gov/ExternalVendorResponseType", partName = "Status")
    public ExternalVendorResponseType receiveABVendorCompletion(
        @WebParam(name = "ExternalVendorRequest", targetNamespace = "http://cms.cciio.mlms.gov/ExternalVendorRequestType", partName = "CompletionRecord")
        ExternalVendorRequestType completionRecord);

}
