//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.mlmsabvendorcompletion;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "MLMSABVendorCompletion", targetNamespace = "http://cms.cciio.mlms.gov/MLMSABVendorCompletion/", wsdlLocation = "WEB-INF/wsdl/wsdl/MLMSABVendorCompletion.wsdl")
public class MLMSABVendorCompletion_Service
    extends Service
{

    private final static URL MLMSABVENDORCOMPLETION_WSDL_LOCATION;
    private final static WebServiceException MLMSABVENDORCOMPLETION_EXCEPTION;
    private final static QName MLMSABVENDORCOMPLETION_QNAME = new QName("http://cms.cciio.mlms.gov/MLMSABVendorCompletion/", "MLMSABVendorCompletion");

    static {
            MLMSABVENDORCOMPLETION_WSDL_LOCATION = gov.mlms.cciio.cms.mlmsabvendorcompletion.MLMSABVendorCompletion_Service.class.getResource("/WEB-INF/wsdl/wsdl/MLMSABVendorCompletion.wsdl");
        WebServiceException e = null;
        if (MLMSABVENDORCOMPLETION_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/wsdl/MLMSABVendorCompletion.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MLMSABVENDORCOMPLETION_EXCEPTION = e;
    }

    public MLMSABVendorCompletion_Service() {
        super(__getWsdlLocation(), MLMSABVENDORCOMPLETION_QNAME);
    }

    public MLMSABVendorCompletion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MLMSABVENDORCOMPLETION_QNAME, features);
    }

    public MLMSABVendorCompletion_Service(URL wsdlLocation) {
        super(wsdlLocation, MLMSABVENDORCOMPLETION_QNAME);
    }

    public MLMSABVendorCompletion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MLMSABVENDORCOMPLETION_QNAME, features);
    }

    public MLMSABVendorCompletion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MLMSABVendorCompletion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MLMSABVendorCompletion
     */
    @WebEndpoint(name = "MLMSABVendorCompletionSOAP")
    public MLMSABVendorCompletion getMLMSABVendorCompletionSOAP() {
        return super.getPort(new QName("http://cms.cciio.mlms.gov/MLMSABVendorCompletion/", "MLMSABVendorCompletionSOAP"), MLMSABVendorCompletion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MLMSABVendorCompletion
     */
    @WebEndpoint(name = "MLMSABVendorCompletionSOAP")
    public MLMSABVendorCompletion getMLMSABVendorCompletionSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://cms.cciio.mlms.gov/MLMSABVendorCompletion/", "MLMSABVendorCompletionSOAP"), MLMSABVendorCompletion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MLMSABVENDORCOMPLETION_EXCEPTION!= null) {
            throw MLMSABVENDORCOMPLETION_EXCEPTION;
        }
        return MLMSABVENDORCOMPLETION_WSDL_LOCATION;
    }

}
