//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.externalvendorrequesttype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The MLMS will use the MLMS server time to record the time the request is received.
 * 
 * <p>Java class for ExternalVendorRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalVendorRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VendorName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LearnerID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CurriculumCode" type="{http://cms.cciio.mlms.gov/ExternalVendorRequestType}CurriculumCodeType"/>
 *         &lt;element name="CurriculumYear" type="{http://cms.cciio.mlms.gov/ExternalVendorRequestType}CurriculumYearType"/>
 *         &lt;element name="CurriculumLanguage" type="{http://cms.cciio.mlms.gov/ExternalVendorRequestType}CurriculumLanguageType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalVendorRequestType", propOrder = {
    "vendorName",
    "learnerID",
    "curriculumCode",
    "curriculumYear",
    "curriculumLanguage"
})
public class ExternalVendorRequestType {

    @XmlElement(name = "VendorName", required = true)
    protected String vendorName;
    @XmlElement(name = "LearnerID", required = true)
    protected String learnerID;
    @XmlElement(name = "CurriculumCode", required = true)
    protected CurriculumCodeType curriculumCode;
    @XmlElement(name = "CurriculumYear", required = true)
    protected CurriculumYearType curriculumYear;
    @XmlElement(name = "CurriculumLanguage", required = true)
    protected CurriculumLanguageType curriculumLanguage;

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the learnerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLearnerID() {
        return learnerID;
    }

    /**
     * Sets the value of the learnerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLearnerID(String value) {
        this.learnerID = value;
    }

    /**
     * Gets the value of the curriculumCode property.
     * 
     * @return
     *     possible object is
     *     {@link CurriculumCodeType }
     *     
     */
    public CurriculumCodeType getCurriculumCode() {
        return curriculumCode;
    }

    /**
     * Sets the value of the curriculumCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurriculumCodeType }
     *     
     */
    public void setCurriculumCode(CurriculumCodeType value) {
        this.curriculumCode = value;
    }

    /**
     * Gets the value of the curriculumYear property.
     * 
     * @return
     *     possible object is
     *     {@link CurriculumYearType }
     *     
     */
    public CurriculumYearType getCurriculumYear() {
        return curriculumYear;
    }

    /**
     * Sets the value of the curriculumYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurriculumYearType }
     *     
     */
    public void setCurriculumYear(CurriculumYearType value) {
        this.curriculumYear = value;
    }

    /**
     * Gets the value of the curriculumLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link CurriculumLanguageType }
     *     
     */
    public CurriculumLanguageType getCurriculumLanguage() {
        return curriculumLanguage;
    }

    /**
     * Sets the value of the curriculumLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurriculumLanguageType }
     *     
     */
    public void setCurriculumLanguage(CurriculumLanguageType value) {
        this.curriculumLanguage = value;
    }

}
