//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.mlmsshopuserprofilecommontype;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DayofWeekAvailabilityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DayofWeekAvailabilityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="available"/>
 *     &lt;enumeration value="unavailable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DayofWeekAvailabilityType")
@XmlEnum
public enum DayofWeekAvailabilityType {

    @XmlEnumValue("available")
    AVAILABLE("available"),
    @XmlEnumValue("unavailable")
    UNAVAILABLE("unavailable");
    private final String value;

    DayofWeekAvailabilityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DayofWeekAvailabilityType fromValue(String v) {
        for (DayofWeekAvailabilityType c: DayofWeekAvailabilityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
