//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.hios.mlms.cciio.cms.assisteragreementstatusresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assisterCertificationStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assisterCertificationStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assisterId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificationAcquiredDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestDatetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="queryDatetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assisterCertificationStatusType", propOrder = {
    "assisterId",
    "certificationName",
    "certificationStatus",
    "certificationAcquiredDate",
    "requestDatetime",
    "queryDatetime"
})
public class AssisterCertificationStatusType {

    @XmlElement(required = true)
    protected String assisterId;
    @XmlElement(required = true)
    protected String certificationName;
    @XmlElement(required = true)
    protected String certificationStatus;
    @XmlElement(required = true)
    protected String certificationAcquiredDate;
    @XmlElement(required = true)
    protected String requestDatetime;
    @XmlElement(required = true)
    protected String queryDatetime;

    /**
     * Gets the value of the assisterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssisterId() {
        return assisterId;
    }

    /**
     * Sets the value of the assisterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssisterId(String value) {
        this.assisterId = value;
    }

    /**
     * Gets the value of the certificationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationName() {
        return certificationName;
    }

    /**
     * Sets the value of the certificationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationName(String value) {
        this.certificationName = value;
    }

    /**
     * Gets the value of the certificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationStatus() {
        return certificationStatus;
    }

    /**
     * Sets the value of the certificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationStatus(String value) {
        this.certificationStatus = value;
    }

    /**
     * Gets the value of the certificationAcquiredDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationAcquiredDate() {
        return certificationAcquiredDate;
    }

    /**
     * Sets the value of the certificationAcquiredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationAcquiredDate(String value) {
        this.certificationAcquiredDate = value;
    }

    /**
     * Gets the value of the requestDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDatetime() {
        return requestDatetime;
    }

    /**
     * Sets the value of the requestDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDatetime(String value) {
        this.requestDatetime = value;
    }

    /**
     * Gets the value of the queryDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryDatetime() {
        return queryDatetime;
    }

    /**
     * Sets the value of the queryDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryDatetime(String value) {
        this.queryDatetime = value;
    }

}
