//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.hios.mlms.cciio.cms.assisteragreementstatusresponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.mlms.cciio.cms.cciiowebservicecommontype.StatusType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assisterAgreementStatus" type="{http://cms.cciio.mlms.hios.gov/AssisterAgreementStatusResponse}assisterCertificationStatusType" maxOccurs="unbounded"/>
 *         &lt;element name="operationStatus" type="{http://cms.cciio.mlms.gov/CCIIOWebServiceCommonType}StatusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assisterAgreementStatus",
    "operationStatus"
})
@XmlRootElement(name = "assisterAgreementStatusResponse")
public class AssisterAgreementStatusResponse {

    @XmlElement(required = true)
    protected List<AssisterCertificationStatusType> assisterAgreementStatus;
    @XmlElement(required = true)
    protected StatusType operationStatus;

    /**
     * Gets the value of the assisterAgreementStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assisterAgreementStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssisterAgreementStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssisterCertificationStatusType }
     * 
     * 
     */
    public List<AssisterCertificationStatusType> getAssisterAgreementStatus() {
        if (assisterAgreementStatus == null) {
            assisterAgreementStatus = new ArrayList<AssisterCertificationStatusType>();
        }
        return this.assisterAgreementStatus;
    }

    /**
     * Gets the value of the operationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getOperationStatus() {
        return operationStatus;
    }

    /**
     * Sets the value of the operationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setOperationStatus(StatusType value) {
        this.operationStatus = value;
    }

}
