//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 08:41:29 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://role.domain.waas.ws.eidm.cms.hhs.gov", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.hhs.cms.eidm.ws.waas.domain.role;
