<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="MLMSRegistrationGap" targetNamespace="http://cms.cciio.mlms.gov/MLMSRegistrationGap/" xmlns:req="http://cms.cciio.mlms.gov/RegistrationGapRequest" xmlns:rsp="http://cms.cciio.mlms.gov/RegistrationGapResponse" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://cms.cciio.mlms.gov/MLMSRegistrationGap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    
    <xsd:schema>
    	<xsd:import namespace="http://cms.cciio.mlms.gov/RegistrationGapResponse" schemaLocation="RegistrationGapResponse.xsd">
    	</xsd:import>
    	<xsd:import namespace="http://cms.cciio.mlms.gov/RegistrationGapRequest" schemaLocation="RegistrationGapRequest.xsd">
    	</xsd:import>
    </xsd:schema>
  </wsdl:types>
 
  <wsdl:message name="RegistrationGapRequestMessage">
  	<wsdl:part element="req:RegistrationGapRequestElement" name="RegistrationGapRequest"/>
  </wsdl:message>
  <wsdl:message name="RegistrationGapResponseMessage">
  	<wsdl:part element="rsp:RegistrationGapResponseElement" name="RegistrationGapResponse"/>
  </wsdl:message>
  <wsdl:portType name="MLMSRegistrationGap">
    <wsdl:operation name="RetrieveMLMSRegistrationGAP">
      <wsdl:input message="tns:RegistrationGapRequestMessage"/>
      <wsdl:output message="tns:RegistrationGapResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MLMSRegistrationGapSOAP" type="tns:MLMSRegistrationGap">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="RetrieveMLMSRegistrationGAP">
      <soap:operation soapAction="http://cms.cciio.mlms.gov/MLMSRegistrationGap/RetrieveRegistrationGAP"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MLMSRegistrationGap">
    <wsdl:port binding="tns:MLMSRegistrationGapSOAP" name="MLMSRegistrationGapSOAP">
      <soap:address location="http://localhost:9080/webservice/MLMSRegistrationGap"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>