//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.14 at 04:24:19 PM EDT 
//


package gov.mlms.cciio.cms.registrationgapresponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.mlms.cciio.cms.registrationgapresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegistrationGapResponseElement_QNAME = new QName("http://cms.cciio.mlms.gov/RegistrationGapResponse", "RegistrationGapResponseElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.mlms.cciio.cms.registrationgapresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistrationGapResponseType }
     * 
     */
    public RegistrationGapResponseType createRegistrationGapResponseType() {
        return new RegistrationGapResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistrationGapResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cms.cciio.mlms.gov/RegistrationGapResponse", name = "RegistrationGapResponseElement")
    public JAXBElement<RegistrationGapResponseType> createRegistrationGapResponseElement(RegistrationGapResponseType value) {
        return new JAXBElement<RegistrationGapResponseType>(_RegistrationGapResponseElement_QNAME, RegistrationGapResponseType.class, null, value);
    }

}
