//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.20 at 03:25:35 PM EDT 
//


package gov.hhs.cms.eidm.ws.waas.domain.userprofile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.hhs.cms.eidm.ws.waas.domain.userprofile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LoaReason_QNAME = new QName("http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", "loaReason");
    private final static QName _Mfa_QNAME = new QName("http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", "mfa");
    private final static QName _DateOfBirth_QNAME = new QName("http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", "dateOfBirth");
    private final static QName _MiddleName_QNAME = new QName("http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", "middleName");
    private final static QName _Ssn_QNAME = new QName("http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", "ssn");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.hhs.cms.eidm.ws.waas.domain.userprofile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserInfoV3Type }
     * 
     */
    public UserInfoV3Type createUserInfoV3Type() {
        return new UserInfoV3Type();
    }

    /**
     * Create an instance of {@link UserInfoV4Type }
     * 
     */
    public UserInfoV4Type createUserInfoV4Type() {
        return new UserInfoV4Type();
    }

    /**
     * Create an instance of {@link ContInfoMultipleRoleType }
     * 
     */
    public ContInfoMultipleRoleType createContInfoMultipleRoleType() {
        return new ContInfoMultipleRoleType();
    }

    /**
     * Create an instance of {@link UserProfileV5Type }
     * 
     */
    public UserProfileV5Type createUserProfileV5Type() {
        return new UserProfileV5Type();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link UserInfoType }
     * 
     */
    public UserInfoType createUserInfoType() {
        return new UserInfoType();
    }

    /**
     * Create an instance of {@link UserInfoV6Type }
     * 
     */
    public UserInfoV6Type createUserInfoV6Type() {
        return new UserInfoV6Type();
    }

    /**
     * Create an instance of {@link BusinContInfoV5Type }
     * 
     */
    public BusinContInfoV5Type createBusinContInfoV5Type() {
        return new BusinContInfoV5Type();
    }

    /**
     * Create an instance of {@link WaaSApplicationInfoType }
     * 
     */
    public WaaSApplicationInfoType createWaaSApplicationInfoType() {
        return new WaaSApplicationInfoType();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link AppUserInfoType }
     * 
     */
    public AppUserInfoType createAppUserInfoType() {
        return new AppUserInfoType();
    }

    /**
     * Create an instance of {@link UserProfileV2Type }
     * 
     */
    public UserProfileV2Type createUserProfileV2Type() {
        return new UserProfileV2Type();
    }

    /**
     * Create an instance of {@link UserInfoV7Type }
     * 
     */
    public UserInfoV7Type createUserInfoV7Type() {
        return new UserInfoV7Type();
    }

    /**
     * Create an instance of {@link UserInfoV5Type }
     * 
     */
    public UserInfoV5Type createUserInfoV5Type() {
        return new UserInfoV5Type();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link UserProfileV6Type }
     * 
     */
    public UserProfileV6Type createUserProfileV6Type() {
        return new UserProfileV6Type();
    }

    /**
     * Create an instance of {@link BusinContInfoV7Type }
     * 
     */
    public BusinContInfoV7Type createBusinContInfoV7Type() {
        return new BusinContInfoV7Type();
    }

    /**
     * Create an instance of {@link AddressV4Type }
     * 
     */
    public AddressV4Type createAddressV4Type() {
        return new AddressV4Type();
    }

    /**
     * Create an instance of {@link AddressV5Type }
     * 
     */
    public AddressV5Type createAddressV5Type() {
        return new AddressV5Type();
    }

    /**
     * Create an instance of {@link UserProfileV4Type }
     * 
     */
    public UserProfileV4Type createUserProfileV4Type() {
        return new UserProfileV4Type();
    }

    /**
     * Create an instance of {@link UserInfoV2Type }
     * 
     */
    public UserInfoV2Type createUserInfoV2Type() {
        return new UserInfoV2Type();
    }

    /**
     * Create an instance of {@link AddressV6Type }
     * 
     */
    public AddressV6Type createAddressV6Type() {
        return new AddressV6Type();
    }

    /**
     * Create an instance of {@link UserInputType }
     * 
     */
    public UserInputType createUserInputType() {
        return new UserInputType();
    }

    /**
     * Create an instance of {@link UserProfileV7Type }
     * 
     */
    public UserProfileV7Type createUserProfileV7Type() {
        return new UserProfileV7Type();
    }

    /**
     * Create an instance of {@link UserProfileType }
     * 
     */
    public UserProfileType createUserProfileType() {
        return new UserProfileType();
    }

    /**
     * Create an instance of {@link AddressV7Type }
     * 
     */
    public AddressV7Type createAddressV7Type() {
        return new AddressV7Type();
    }

    /**
     * Create an instance of {@link UserProfileV3Type }
     * 
     */
    public UserProfileV3Type createUserProfileV3Type() {
        return new UserProfileV3Type();
    }

    /**
     * Create an instance of {@link BusinContInfoV6Type }
     * 
     */
    public BusinContInfoV6Type createBusinContInfoV6Type() {
        return new BusinContInfoV6Type();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", name = "loaReason")
    public JAXBElement<String> createLoaReason(String value) {
        return new JAXBElement<String>(_LoaReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", name = "mfa")
    public JAXBElement<String> createMfa(String value) {
        return new JAXBElement<String>(_Mfa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", name = "dateOfBirth")
    public JAXBElement<XMLGregorianCalendar> createDateOfBirth(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateOfBirth_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", name = "middleName")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://userprofile.domain.waas.ws.eidm.cms.hhs.gov", name = "ssn")
    public JAXBElement<String> createSsn(String value) {
        return new JAXBElement<String>(_Ssn_QNAME, String.class, null, value);
    }

}
