//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 01:06:34 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cms.cciio.mlms.gov/FileDescriptionType")
package gov.mlms.cciio.cms.filedescriptiontype;
