//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 01:06:34 PM EDT 
//


package gov.mlms.cciio.cms.filedescriptiontype;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.mlms.cciio.cms.mlmsshopuserprofilecommontype.AddressType;
import gov.mlms.cciio.cms.mlmsshopuserprofilecommontype.UserPreferencesType;
import gov.mlms.cciio.cms.mlmsshopuserprofilecommontype.UserType;


/**
 * <p>Java class for ShopRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShopRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserInfo" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}UserType"/>
 *         &lt;element name="AddressInfo" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}AddressType"/>
 *         &lt;element name="PreferenceInfo" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}UserPreferencesType"/>
 *         &lt;element name="CompletionInfo" type="{http://cms.cciio.mlms.gov/FileDescriptionType}CompletionInfoType" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShopRecordType", propOrder = {
    "userInfo",
    "addressInfo",
    "preferenceInfo",
    "completionInfo"
})
public class ShopRecordType {

    @XmlElement(name = "UserInfo", required = true)
    protected UserType userInfo;
    @XmlElement(name = "AddressInfo", required = true)
    protected AddressType addressInfo;
    @XmlElement(name = "PreferenceInfo", required = true)
    protected UserPreferencesType preferenceInfo;
    @XmlElement(name = "CompletionInfo")
    protected List<CompletionInfoType> completionInfo;

    /**
     * Gets the value of the userInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUserInfo() {
        return userInfo;
    }

    /**
     * Sets the value of the userInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUserInfo(UserType value) {
        this.userInfo = value;
    }

    /**
     * Gets the value of the addressInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddressInfo() {
        return addressInfo;
    }

    /**
     * Sets the value of the addressInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddressInfo(AddressType value) {
        this.addressInfo = value;
    }

    /**
     * Gets the value of the preferenceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UserPreferencesType }
     *     
     */
    public UserPreferencesType getPreferenceInfo() {
        return preferenceInfo;
    }

    /**
     * Sets the value of the preferenceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPreferencesType }
     *     
     */
    public void setPreferenceInfo(UserPreferencesType value) {
        this.preferenceInfo = value;
    }

    /**
     * Gets the value of the completionInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the completionInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompletionInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompletionInfoType }
     * 
     * 
     */
    public List<CompletionInfoType> getCompletionInfo() {
        if (completionInfo == null) {
            completionInfo = new ArrayList<CompletionInfoType>();
        }
        return this.completionInfo;
    }

}
