//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.externalvendorrequesttype;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.mlms.cciio.cms.externalvendorrequesttype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExternalVendorRequest_QNAME = new QName("http://cms.cciio.mlms.gov/ExternalVendorRequestType", "ExternalVendorRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.mlms.cciio.cms.externalvendorrequesttype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalVendorRequestType }
     * 
     */
    public ExternalVendorRequestType createExternalVendorRequestType() {
        return new ExternalVendorRequestType();
    }

    /**
     * Create an instance of {@link CurriculumLanguageType }
     * 
     */
    public CurriculumLanguageType createCurriculumLanguageType() {
        return new CurriculumLanguageType();
    }

    /**
     * Create an instance of {@link CurriculumCodeType }
     * 
     */
    public CurriculumCodeType createCurriculumCodeType() {
        return new CurriculumCodeType();
    }

    /**
     * Create an instance of {@link CurriculumYearType }
     * 
     */
    public CurriculumYearType createCurriculumYearType() {
        return new CurriculumYearType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalVendorRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cms.cciio.mlms.gov/ExternalVendorRequestType", name = "ExternalVendorRequest")
    public JAXBElement<ExternalVendorRequestType> createExternalVendorRequest(ExternalVendorRequestType value) {
        return new JAXBElement<ExternalVendorRequestType>(_ExternalVendorRequest_QNAME, ExternalVendorRequestType.class, null, value);
    }

}
