//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package gov.mlms.cciio.cms.registrationgapresponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.mlms.cciio.cms.agentbrokertrainingcompletionstatus.UserTrainingResponseType;
import gov.mlms.cciio.cms.cciiowebservicecommontype.ErrorCodeType;
import gov.mlms.cciio.cms.cciiowebservicecommontype.StatusType;


/**
 * <p>Java class for RegistrationGapResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistrationGapResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegistrationGapUserType" type="{http://cms.cciio.mlms.gov/AgentBrokerTrainingCompletionStatus}UserTrainingResponseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StatusCode" type="{http://cms.cciio.mlms.gov/CCIIOWebServiceCommonType}StatusType"/>
 *         &lt;element name="ErrorCode" type="{http://cms.cciio.mlms.gov/CCIIOWebServiceCommonType}errorCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistrationGapResponseType", propOrder = {
    "registrationGapUserType",
    "statusCode",
    "errorCode"
})
public class RegistrationGapResponseType {

    @XmlElement(name = "RegistrationGapUserType")
    protected List<UserTrainingResponseType> registrationGapUserType;
    @XmlElement(name = "StatusCode", required = true)
    protected StatusType statusCode;
    @XmlElement(name = "ErrorCode", required = true)
    protected ErrorCodeType errorCode;

    /**
     * Gets the value of the registrationGapUserType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the registrationGapUserType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegistrationGapUserType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserTrainingResponseType }
     * 
     * 
     */
    public List<UserTrainingResponseType> getRegistrationGapUserType() {
        if (registrationGapUserType == null) {
            registrationGapUserType = new ArrayList<UserTrainingResponseType>();
        }
        return this.registrationGapUserType;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatusCode(StatusType value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorCodeType }
     *     
     */
    public ErrorCodeType getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorCodeType }
     *     
     */
    public void setErrorCode(ErrorCodeType value) {
        this.errorCode = value;
    }

}
