//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 01:47:13 PM EDT 
//


package gov.mlms.cciio.cms.mlmsshopincrementalfiletype;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FileIdentifier" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="FileDateTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[2][0-9][0-9][0-9]/[0-1][0-9]/[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FileRecordCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="FileTypeInfo" type="{http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType}FileTypeInfoType"/>
 *         &lt;element name="IncrementalRecord" type="{http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType}ShopRecordType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileIdentifier",
    "fileDateTime",
    "fileRecordCount",
    "fileTypeInfo",
    "incrementalRecord"
})
@XmlRootElement(name = "FileDescriptionType")
public class FileDescriptionType {

    @XmlElement(name = "FileIdentifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String fileIdentifier;
    @XmlElement(name = "FileDateTime", required = true)
    protected String fileDateTime;
    @XmlElement(name = "FileRecordCount", required = true)
    protected BigInteger fileRecordCount;
    @XmlElement(name = "FileTypeInfo", required = true)
    protected FileTypeInfoType fileTypeInfo;
    @XmlElement(name = "IncrementalRecord", required = true)
    protected List<ShopRecordType> incrementalRecord;

    /**
     * Gets the value of the fileIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileIdentifier() {
        return fileIdentifier;
    }

    /**
     * Sets the value of the fileIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileIdentifier(String value) {
        this.fileIdentifier = value;
    }

    /**
     * Gets the value of the fileDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDateTime() {
        return fileDateTime;
    }

    /**
     * Sets the value of the fileDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDateTime(String value) {
        this.fileDateTime = value;
    }

    /**
     * Gets the value of the fileRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFileRecordCount() {
        return fileRecordCount;
    }

    /**
     * Sets the value of the fileRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFileRecordCount(BigInteger value) {
        this.fileRecordCount = value;
    }

    /**
     * Gets the value of the fileTypeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FileTypeInfoType }
     *     
     */
    public FileTypeInfoType getFileTypeInfo() {
        return fileTypeInfo;
    }

    /**
     * Sets the value of the fileTypeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileTypeInfoType }
     *     
     */
    public void setFileTypeInfo(FileTypeInfoType value) {
        this.fileTypeInfo = value;
    }

    /**
     * Gets the value of the incrementalRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incrementalRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncrementalRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShopRecordType }
     * 
     * 
     */
    public List<ShopRecordType> getIncrementalRecord() {
        if (incrementalRecord == null) {
            incrementalRecord = new ArrayList<ShopRecordType>();
        }
        return this.incrementalRecord;
    }

}
