//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 01:47:13 PM EDT 
//


package gov.mlms.cciio.cms.mlmsshopincrementalfiletype;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.mlms.cciio.cms.mlmsshopincrementalfiletype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.mlms.cciio.cms.mlmsshopincrementalfiletype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileDescriptionType }
     * 
     */
    public FileDescriptionType createFileDescriptionType() {
        return new FileDescriptionType();
    }

    /**
     * Create an instance of {@link FileTypeInfoType }
     * 
     */
    public FileTypeInfoType createFileTypeInfoType() {
        return new FileTypeInfoType();
    }

    /**
     * Create an instance of {@link ShopRecordType }
     * 
     */
    public ShopRecordType createShopRecordType() {
        return new ShopRecordType();
    }

    /**
     * Create an instance of {@link CompletionInfoType }
     * 
     */
    public CompletionInfoType createCompletionInfoType() {
        return new CompletionInfoType();
    }

}
