//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 01:47:13 PM EDT 
//


package gov.mlms.cciio.cms.mlmsshopuserprofilecommontype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DaysOfWeekType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DaysOfWeekType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Monday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *         &lt;element name="Tuesday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *         &lt;element name="Wednesday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *         &lt;element name="Thursday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *         &lt;element name="Friday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *         &lt;element name="Saturday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *         &lt;element name="Sunday" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DayofWeekAvailabilityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DaysOfWeekType", propOrder = {
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday"
})
public class DaysOfWeekType {

    @XmlElement(name = "Monday", required = true)
    protected DayofWeekAvailabilityType monday;
    @XmlElement(name = "Tuesday", required = true)
    protected DayofWeekAvailabilityType tuesday;
    @XmlElement(name = "Wednesday", required = true)
    protected DayofWeekAvailabilityType wednesday;
    @XmlElement(name = "Thursday", required = true)
    protected DayofWeekAvailabilityType thursday;
    @XmlElement(name = "Friday", required = true)
    protected DayofWeekAvailabilityType friday;
    @XmlElement(name = "Saturday", required = true)
    protected DayofWeekAvailabilityType saturday;
    @XmlElement(name = "Sunday", required = true)
    protected DayofWeekAvailabilityType sunday;

    /**
     * Gets the value of the monday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getMonday() {
        return monday;
    }

    /**
     * Sets the value of the monday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setMonday(DayofWeekAvailabilityType value) {
        this.monday = value;
    }

    /**
     * Gets the value of the tuesday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getTuesday() {
        return tuesday;
    }

    /**
     * Sets the value of the tuesday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setTuesday(DayofWeekAvailabilityType value) {
        this.tuesday = value;
    }

    /**
     * Gets the value of the wednesday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getWednesday() {
        return wednesday;
    }

    /**
     * Sets the value of the wednesday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setWednesday(DayofWeekAvailabilityType value) {
        this.wednesday = value;
    }

    /**
     * Gets the value of the thursday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getThursday() {
        return thursday;
    }

    /**
     * Sets the value of the thursday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setThursday(DayofWeekAvailabilityType value) {
        this.thursday = value;
    }

    /**
     * Gets the value of the friday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getFriday() {
        return friday;
    }

    /**
     * Sets the value of the friday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setFriday(DayofWeekAvailabilityType value) {
        this.friday = value;
    }

    /**
     * Gets the value of the saturday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getSaturday() {
        return saturday;
    }

    /**
     * Sets the value of the saturday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setSaturday(DayofWeekAvailabilityType value) {
        this.saturday = value;
    }

    /**
     * Gets the value of the sunday property.
     * 
     * @return
     *     possible object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public DayofWeekAvailabilityType getSunday() {
        return sunday;
    }

    /**
     * Sets the value of the sunday property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayofWeekAvailabilityType }
     *     
     */
    public void setSunday(DayofWeekAvailabilityType value) {
        this.sunday = value;
    }

}
