//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-07/07/2014 12:56 PM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 01:47:13 PM EDT 
//


package gov.mlms.cciio.cms.mlmsshopuserprofilecommontype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserPreferencesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserPreferencesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WorkingHours" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}WorkingHoursType"/>
 *         &lt;element name="WorkingDays" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}DaysOfWeekType"/>
 *         &lt;element name="PreferredLanguage" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}languageType"/>
 *         &lt;element name="PreferredContactMethod">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Email address"/>
 *               &lt;enumeration value="Mailing address"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SearchIndicator" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}SearchIndicatorType"/>
 *         &lt;element name="AgencyInfo" type="{http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType}AgencyInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserPreferencesType", propOrder = {
    "workingHours",
    "workingDays",
    "preferredLanguage",
    "preferredContactMethod",
    "searchIndicator",
    "agencyInfo"
})
public class UserPreferencesType {

    @XmlElement(name = "WorkingHours", required = true)
    protected WorkingHoursType workingHours;
    @XmlElement(name = "WorkingDays", required = true)
    protected DaysOfWeekType workingDays;
    @XmlElement(name = "PreferredLanguage", required = true)
    protected LanguageType preferredLanguage;
    @XmlElement(name = "PreferredContactMethod", required = true)
    protected String preferredContactMethod;
    @XmlElement(name = "SearchIndicator", required = true)
    protected SearchIndicatorType searchIndicator;
    @XmlElement(name = "AgencyInfo", required = true)
    protected AgencyInfoType agencyInfo;

    /**
     * Gets the value of the workingHours property.
     * 
     * @return
     *     possible object is
     *     {@link WorkingHoursType }
     *     
     */
    public WorkingHoursType getWorkingHours() {
        return workingHours;
    }

    /**
     * Sets the value of the workingHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkingHoursType }
     *     
     */
    public void setWorkingHours(WorkingHoursType value) {
        this.workingHours = value;
    }

    /**
     * Gets the value of the workingDays property.
     * 
     * @return
     *     possible object is
     *     {@link DaysOfWeekType }
     *     
     */
    public DaysOfWeekType getWorkingDays() {
        return workingDays;
    }

    /**
     * Sets the value of the workingDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaysOfWeekType }
     *     
     */
    public void setWorkingDays(DaysOfWeekType value) {
        this.workingDays = value;
    }

    /**
     * Gets the value of the preferredLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageType }
     *     
     */
    public LanguageType getPreferredLanguage() {
        return preferredLanguage;
    }

    /**
     * Sets the value of the preferredLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *     
     */
    public void setPreferredLanguage(LanguageType value) {
        this.preferredLanguage = value;
    }

    /**
     * Gets the value of the preferredContactMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredContactMethod() {
        return preferredContactMethod;
    }

    /**
     * Sets the value of the preferredContactMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredContactMethod(String value) {
        this.preferredContactMethod = value;
    }

    /**
     * Gets the value of the searchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link SearchIndicatorType }
     *     
     */
    public SearchIndicatorType getSearchIndicator() {
        return searchIndicator;
    }

    /**
     * Sets the value of the searchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchIndicatorType }
     *     
     */
    public void setSearchIndicator(SearchIndicatorType value) {
        this.searchIndicator = value;
    }

    /**
     * Gets the value of the agencyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AgencyInfoType }
     *     
     */
    public AgencyInfoType getAgencyInfo() {
        return agencyInfo;
    }

    /**
     * Sets the value of the agencyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgencyInfoType }
     *     
     */
    public void setAgencyInfo(AgencyInfoType value) {
        this.agencyInfo = value;
    }

}
