//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.mlms.cciio.cms.smallbusinesshealthoption;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.mlms.cciio.cms.shopagreementstatusrequesttype.UserId;
import gov.mlms.cciio.cms.shopagreementstatusresponsetype.ShopAgreementStatusResponse;

@WebService(name = "SmallBusinessHealthOption", targetNamespace = "http://cms.cciio.mlms.gov/SmallBusinessHealthOption/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.mlms.cciio.cms.cciiowebservicecommontype.ObjectFactory.class,
    gov.mlms.cciio.cms.shopagreementstatusrequesttype.ObjectFactory.class,
    gov.mlms.cciio.cms.shopagreementstatusresponsetype.ObjectFactory.class
})
public interface SmallBusinessHealthOption {


    /**
     * 
     * @param userId
     * @return
     *     returns gov.mlms.cciio.cms.shopagreementstatusresponsetype.ShopAgreementStatusResponse
     */
    @WebMethod(operationName = "RetrieveShopAgreementStatus", action = "http://cms.cciio.mlms.gov/SmallBusinessHealthOption/RetrieveShopAgreementStatus")
    @WebResult(name = "shopAgreementStatusResponse", targetNamespace = "http://cms.cciio.mlms.gov/ShopAgreementStatusResponseType", partName = "ShopAgreementStatus")
    public ShopAgreementStatusResponse retrieveShopAgreementStatus(
        @WebParam(name = "userId", targetNamespace = "http://cms.cciio.mlms.gov/ShopAgreementStatusRequestType", partName = "userId")
        UserId userId);

}
