//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.cms.hios_api_types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssisterCertificationStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssisterCertificationStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Certified"/>
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="Not Certified"/>
 *     &lt;enumeration value="De-Certified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssisterCertificationStatusType")
@XmlEnum
public enum AssisterCertificationStatusType {

    @XmlEnumValue("Certified")
    CERTIFIED("Certified"),
    NA("NA"),
    @XmlEnumValue("Not Certified")
    NOT_CERTIFIED("Not Certified"),
    @XmlEnumValue("De-Certified")
    DE_CERTIFIED("De-Certified");
    private final String value;

    AssisterCertificationStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AssisterCertificationStatusType fromValue(String v) {
        for (AssisterCertificationStatusType c: AssisterCertificationStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
