//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.cms.hios_api_types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Assister complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assister">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssisterID" type="{http://cms.gov/hios-api-types}AssisterIDType"/>
 *         &lt;element name="Grantee" type="{http://cms.gov/hios-api-types}Grantee"/>
 *         &lt;element name="AssisterContact" type="{http://cms.gov/hios-api-types}ContactType"/>
 *         &lt;element name="CertificationStatus" type="{http://cms.gov/hios-api-types}AssisterCertificationStatusType"/>
 *         &lt;element name="CertificationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assister", propOrder = {
    "assisterID",
    "grantee",
    "assisterContact",
    "certificationStatus",
    "certificationDate"
})
public class Assister {

    @XmlElement(name = "AssisterID", required = true)
    protected String assisterID;
    @XmlElement(name = "Grantee", required = true)
    protected Grantee grantee;
    @XmlElement(name = "AssisterContact", required = true)
    protected ContactType assisterContact;
    @XmlElement(name = "CertificationStatus", required = true)
    protected AssisterCertificationStatusType certificationStatus;
    @XmlElement(name = "CertificationDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certificationDate;

    /**
     * Gets the value of the assisterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssisterID() {
        return assisterID;
    }

    /**
     * Sets the value of the assisterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssisterID(String value) {
        this.assisterID = value;
    }

    /**
     * Gets the value of the grantee property.
     * 
     * @return
     *     possible object is
     *     {@link Grantee }
     *     
     */
    public Grantee getGrantee() {
        return grantee;
    }

    /**
     * Sets the value of the grantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grantee }
     *     
     */
    public void setGrantee(Grantee value) {
        this.grantee = value;
    }

    /**
     * Gets the value of the assisterContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactType }
     *     
     */
    public ContactType getAssisterContact() {
        return assisterContact;
    }

    /**
     * Sets the value of the assisterContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactType }
     *     
     */
    public void setAssisterContact(ContactType value) {
        this.assisterContact = value;
    }

    /**
     * Gets the value of the certificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AssisterCertificationStatusType }
     *     
     */
    public AssisterCertificationStatusType getCertificationStatus() {
        return certificationStatus;
    }

    /**
     * Sets the value of the certificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssisterCertificationStatusType }
     *     
     */
    public void setCertificationStatus(AssisterCertificationStatusType value) {
        this.certificationStatus = value;
    }

    /**
     * Gets the value of the certificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificationDate() {
        return certificationDate;
    }

    /**
     * Sets the value of the certificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificationDate(XMLGregorianCalendar value) {
        this.certificationDate = value;
    }

}
