//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package gov.cms.hios_api_types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grantee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grantee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GranteeOrganization" type="{http://cms.gov/hios-api-types}GranteeOrganization"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grantee", propOrder = {
    "granteeOrganization"
})
public class Grantee {

    @XmlElement(name = "GranteeOrganization", required = true)
    protected GranteeOrganization granteeOrganization;

    /**
     * Gets the value of the granteeOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link GranteeOrganization }
     *     
     */
    public GranteeOrganization getGranteeOrganization() {
        return granteeOrganization;
    }

    /**
     * Sets the value of the granteeOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link GranteeOrganization }
     *     
     */
    public void setGranteeOrganization(GranteeOrganization value) {
        this.granteeOrganization = value;
    }

}
